/**
 * @description       : 
 * @author            : Iamsfdeveloper
 * @group             : 
 * @last modified on  : 04-09-2021
 * @last modified by  : Iamsfdeveloper
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   03-31-2021   Iamsfdeveloper   Initial Version
**/
public without sharing class HA_CreateDonations_Queueable  { public HA_CreateDonations_Queueable(){}}