/**
 * @description       : 
 * @author            : Iamsfdeveloper
 * @group             : 
 * @last modified on  : 06-15-2021
 * @last modified by  : Iamsfdeveloper
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   06-15-2021   Iamsfdeveloper   Initial Version
**/
global class RecurringDonations_TDTM_Runnable  {
    public RecurringDonations_TDTM_Runnable(){
        
    }
    
}